apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
spec:
  ports:
  - port: {{ .Values.service.port }}
    {{- if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{- else }}
    targetPort: {{ .Values.service.port }}
    {{- end }}
    protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
  selector:
    app: techtrends
