apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
spec:
  ports:
  - port: 4111
    targetPort: 3111
    protocol: TCP
  type: ClusterIP
  selector:
    app: techtrends
